---

- hosts: all
  become: true
  pre_tasks:
    - name: Bootstrap Python2 for Ansible
      raw: test -e /usr/bin/python || (apt -qq update && apt install -qq python-minimal)
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Add an apt signing key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present
  roles:
    - ufw

- hosts: mongo
  gather_facts: no
  roles:
    - role: mongodb
      when: "'mongo_master' in group_names"

- hosts: mongo
  gather_facts: no
  roles:
    - role: mongodb
      when: "'mongo_replicas' in group_names"
